version: 0.7.0.a

load_order:
    - "global-variables"
    - "global-functions"
    - "global-functions.array"
    - "global-functions.string"
    - "global-functions.network"
    - "global-functions.datetime"
    - "global-functions.random"
    - "global-functions.package"
    - "global-functions.config"
    - "global-functions.runner"
    - "global-functions.unicode"
    - "global-functions.misc"

essential_package_list:
    - "global-variables"
    - "global-functions"
    - "global-functions.array"
    - "global-functions.string"
    - "global-functions.network"
    - "global-functions.datetime"
    - "global-functions.random"
    - "global-functions.package"
    - "global-functions.config"
    - "global-functions.runner"
    - "global-functions.unicode"
    - "global-functions.misc"
    - "tool.http"
    - "tool.remote"
    - "rospm.feature"
    - "rospm.state"
    - "rospm.action"
    - "rospm.reset"
    - "rospm"
